# -*- coding: utf-8 -*-
"""K-Means Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LTwPV6eEKqM2VVIlK6C_MI02vRI7v4jD
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans

# Task 1: Generate 500 samples with 4 centers
X, _ = make_blobs(n_samples=500, centers=4, cluster_std=1.0, random_state=42)

# Task 2: Elbow Method
inertia = []
K_range = range(1, 11) # Starting from 1 to 10
for k in K_range:
    km = KMeans(n_clusters=k, n_init=10, random_state=42)
    km.fit(X)
    inertia.append(km.inertia_)

# Fix dimensions for plotting
plt.figure(figsize=(8, 5))
plt.plot(list(K_range), inertia, marker='o')
plt.title('Elbow Method for Optimal K')
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Inertia')
plt.grid(True)
plt.show()

# Task 3: Final Model based on Elbow (K=4)
final_model = KMeans(n_clusters=4, n_init=10, random_state=42)
y_kmeans = final_model.fit_predict(X)

plt.scatter(X[:, 0], X[:, 1], c=y_kmeans, s=50, cmap='viridis')
plt.scatter(final_model.cluster_centers_[:, 0], final_model.cluster_centers_[:, 1], s=200, c='red', marker='X', label='Centroids')
plt.title('Final Clustering Result (K=4)')
plt.legend()
plt.show()

# Task 4: Report Inertia values
print(f"Inertia for K=3: {KMeans(n_clusters=3, n_init=10).fit(X).inertia_:.2f}")
print(f"Inertia for K=4 (Optimal): {final_model.inertia_:.2f}")
print(f"Inertia for K=5: {KMeans(n_clusters=5, n_init=10).fit(X).inertia_:.2f}")